language: node_js
node_js:
  - '0.10'

branches:
  except:
    - /^g3_.*$/

env:
  matrix:
    - JOB=unit BROWSER_PROVIDER=bs
    - JOB=e2e TEST_TARGET=jqlite
    - JOB=e2e TEST_TARGET=jquery
  global:
    - LOGS_DIR=/tmp/angular-build/logs
    - BROWSER_PROVIDER_READY_FILE=/tmp/tunnel-ready
    - secure: "cKJURNx6BlASpSuel2segPINQvvx20x98kwwtd1wnsISVbnfI9MQCxM7M39PILFZyhwDg/9uw6Kgh/OZAYyDbw88UW7gyqzvfb3JpkA7/bZU5RJnneWnsuC8xi+jcmV3neiNLylHNfRAxpSYqNk7W9BrxH8LpRr6/dXFG6fVFLQ="
    - secure: "NrBu+pdROzvQF3sbEi0KK2QfdMxYsbuvP4r2a6bpljfcvdCXTQFHqUmW5k9X7JUaFD0mrFLGo0+P53E2TW9VsVSKDRsbcaoro4GPYt/J5g7gizbiU0z+P8N8yrHR7siOC6fWeGYS78cw+NO+22ronVSnsDnkznOIiv/zi1dgWOY="

install:
  # - npm config set registry http://23.251.144.68
  # Disable the spinner, it looks bad on Travis
  - npm config set spin false
  # Log HTTP requests
  - npm config set loglevel http
  - time ./scripts/travis/npm-bundle-deps.sh
  - time npm install

before_script:
  - mkdir -p $LOGS_DIR
  - ./lib/browser-stack/start-tunnel.sh
  - npm install -g grunt-cli
  - grunt package
  - ./scripts/travis/wait_for_browser_provider.sh

script:
  - ./scripts/travis/build.sh

after_script:
  - ./scripts/travis/print_logs.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d2120f3f2bb39a4531b2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
